# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-KR
  languageName: 한국어
  contentDir: content/ko

  menu:
    main:
      - name: 홈
        url: "/"
        weight: 1
      - name: 자기소개
        url: "/about/"
        weight: 2

en:
  languageCode: en-us
  languageName: English
  contentDir: content/en

  menu:
    main:
      - name: Home
        url: "/en/"
        weight: 1
      - name: About
        url: "/about/"
        weight: 2
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  
# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
