# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
    #한국어 메뉴
  - name: 홈
    url: /
    weight: 10
    language: ko
  - name: 자기소개
    url: about/
    weight: 20
    language: ko
  - name: 프로젝트
    url: projects/
    weight: 30
    language: ko
  - name: 갤러리
    url: gallery/
    weight: 40
    language: ko
  - name: 학교생활
    identifier: activity
    weight: 50
    language: ko
  - name: 커리큘럼
    url: curriculum/
    parent: activity
    weight: 1
    language: ko
  - name: 동아리
    url: dongari/
    parent: activity
    weight: 2
    language: ko
  
  - name: 경력
    identifier: careers
    weight: 60
    language: ko

  - name: 수상
    url: award/
    parent: careers
    weight: 1
    language: ko
  - name: 자격증
    url: qualifications/
    parent: careers
    weight: 2
    language: ko
 
  - name: 연락처
    url: contact/
    weight: 70
    language: ko

    #영어 메뉴
  - name: Home
    url: /en/
    weight: 10
    language: en
  - name: About
    url: /en/about/
    weight: 20
    language: en
  - name: Projects
    url: /en/projects/
    weight: 30
    language: en
  - name: Gallery
    url: /en/gallery/
    weight: 40
    language: en
  - name: School Life
    identifier: activity
    weight: 50
    language: en
  - name: Curriculum
    url: /en/curriculum/
    parent: activity
    weight: 1
    language: en
  - name: Club
    url: /en/dongari/
    parent: activity
    weight: 2
    language: en
  
  - name: Career
    identifier: careers
    weight: 60
    language: en
  - name: Award
    url: /en/award/
    parent: careers
    weight: 1
    language: en
  - name: Certificate
    url: /en/qualifications/
    parent: careers
    weight: 2
    language: en
  - name: Contact
    url: /en/contact/
    weight: 70
    language: en